# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: |
          11
          17
          21
          8
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        export JAVA_HOME=$JAVA_HOME_8_x86
        mvn -B clean source:jar install
    - name: Test with JDK 11
      run: |
        export JAVA_HOME=$JAVA_HOME_11_x86
        mvn -B clean test
    - name: Test with JDK 17
      run: |
        export JAVA_HOME=$JAVA_HOME_17_x86
        mvn -B clean test
    - name: Test with JDK 21
      run: |
        export JAVA_HOME=$JAVA_HOME_21_x86
        mvn -B clean test
